### PR TITLE
Update `dist/index.js` to include changes from #17

### PR DESCRIPTION
**Pull request by timmfin**
Probably should bump the version too (and publish), but I didn’t do that in this PR.

### CODE REVIEW

**Comment by sample-usr** [comment]
Hi @timmfin can you explain the PR a bit more. Also, dist/index.js is the generated source code, if you need to submit a PR please modify the code in src/

**Comment by timmfin** [comment]
Apologies for not being more clear. I was submitting this PR because the generated source was out of sync with master. https://github.com/razagill/react-phone-input/pull/17 had been merged, but `dist/index.js` wasn't updated afterward. Maybe I'm missing something, but my expectation was that the `dist/index.js` file in the repo would be in sync with the rest of the code in the repo.

Maybe you only update `dist/index.js` before tagging a new version and publishing? (Though both `1.1.1` and `1.1.2` seem to be tagged and published without updating `dist/index.js` either)

**Comment by sample-usr** [comment]
@timmfin I see the confusion. Actually, I wanted to get some more features in before releasing a new version. That's why I merged the PR from #17 but didn't recompile the app or publish it to npm.
I'm working on a few new methods and I'll be releasing a new version in the next couple of weeks. Sorry for all the confusion.

**Comment by timmfin** [comment]
Got it, no biggie. I think we are going to need to tweak the webpack build anyway for our needs. 

Thanks for the help!

**Pull request closed without merging**
